@base=https://fcwsywnkp0.execute-api.us-east-1.amazonaws.com/test
@auth0token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIiwiaXNzIjoiaHR0cHM6Ly94b3BzLWNvbnRyb2wtY2VudGVyLWRldi51cy5hdXRoMC5jb20vIn0..QjChtmjuSAIg-Lnc.HFh6paeR5avkcn3EduanUAB-naROEYOz6kUFxYlfR0lgDnVeIHrZEv25jesoXHlBFtN45jmQda-PBWGBuHc39SgmLBRJmygQHapBFDdJfA_fEW3rurzmnOkyhG3QPbx6IZFFpQn6BkU9vL1OGFPHwNC4WkUOHl8Cu3klQfepmCYHH3_ak6vDhFZrDYVbG-xENyz5439YNlsF6q-gsaMhl0VIc9CD7FbJgOp0GpxFR_oKzz5HzZ4cJaHRF4wGBOjbuV6gZJU_KhvkBmoGVKGWZq3-kTW4sFxkvkVTr-CscBLzQGuDXcOnJxYW0YHAMR96pm52_xGrd94gBPQGMud1yyVP56Py_9Ly.1Pwqc146U2EUxQXLQH-q6w
### User Admin
# QueryString:
#   page: number DEFAULT = 1
#   perPage: number DEFAULT = 10
# Response.data:
  # {
    # "users": {
        # "user_id": number,
        # "first_name": string,
        # "last_name": string,
        # "phone_number_mobile": string,
        # "status": string,
        # "picture": string
        # "business_unit": string,
        # "email": string,
        # "country": string
        # "roles": string[]
#   }[]
# }
GET {{base}}/users
Authorization: {{auth0token}}

### User Admin
# Response.data:
  # {
    # "statistic": {
      # "total": number,
      # "active": number
    # }
# }
GET {{base}}/users/statistic
Authorization: {{auth0token}}

### User Admin
# Body:
#   "first_name": string,
#   "last_name": string,
#   "email": string
#   "phone_number_mobile": string,
#   "country": string,
#   "status": string,
#   "business_unit": string,
#   "password": string
# Response.data: 
# {
  #     user_id: string
# }
POST {{base}}/users
Authorization: {{auth0token}}
Content-Type: application/json
{
  "first_name": "Bohdan",
  "last_name": "Tkachuk",
  "email": "maksandbodya@gmail.com",
  "phone_number_mobile": "+380000000000",
  "role": "user",
  "country": "United Kingdom",
  "status": "Active",
  "business_unit": "Seed BK-UK",
  "password": "Admin123"
}

### User Admin
# Path Parameters:
#   id: number - id of user that should be updated
# Body: - all values are optional
#   "first_name": string,             *** If you change one of names, you should put in request body the second
#   "last_name": string,              *** If you change one of names, you should put in request body the second
#   "email": string,                  *** You can't update email and password at the same time
#   "phone_number_mobile": string,
#   "country": string,
#   "status": string,
#   "business_unit": string,
#   "password": string                *** You can't update email and password at the same time
PUT {{base}}/users/:id
Authorization: {{auth0token}}
Content-Type: application/json
    {
      "first_name": "Gregory",
      "last_name": "House",
    }

### User Admin
# Path Parameters:
#   id: string - id of user that should be updated
# Body: - all values are optional
#   "role": string
PUT {{base}}/users/role/:id
Authorization: {{auth0token}}
Content-Type: application/json
{
    "role": "manager"
}

### Requests
# QueryString:
#   last: number - the number of days for which the data is received
#   page: number DEFAULT = 1
#   perPage: number DEFAULT = 10
#   sortBy: keyof Response.data.requests DEFAULT = 'request_id'
#   direction: 'asc' | 'desc' DEFAULT = 'asc'
#   filter: 'needs_verification' | 'urgent' | 'in_transit' | 'in_deploy' DEFAULT = 'all_requests'
# Response.data: 
# {
    # requests: {
    #     request_id: any
    #     requestor: string
    #     notes: string
    #     date_opened?: string
    #     date_closed: string
    #     impacted_user_id: string
    #     location: string
    #     status: string
    #     category: string
    #     serial_numbers: string[]
    #     incidents_count: unknown
    #     priority: number
    #     events: {
    #         event_id: number
    #         priority: number
    #         event_key: string
    #         long_desc: string
    #         event_date: string
    #         event_type: string
    #         short_desc: string
    #         incident: {
    #             incident_id: number
    #             start_date: string
    #             last_modified: string
    #         }
    #     }[]
    # }[]
# }
GET {{base}}/requests
Authorization: {{auth0token}}

### Requests
# Response.data: 
# {
#     work_order_id: number
#     requsetor: string
#     runbook: string
#     events: number[]
#     incidents: number[]
#     notes: string[]
# }
GET {{base}}/requests/:id
Authorization: {{auth0token}}

### Control Center
GET {{base}}/requests/statistic
Authorization: {{auth0token}}

### Control Center / Incidents
# QueryString:
#   page: number DEFAULT = 1
#   perPage: number DEFAULT = 10
#   countryCode: string
#   type: string
# Response.data:
  # {
    # incidents: {
      # "incident_id": number,
      # "action": string
      # "latitude": number
      # "longitude": number,
      # "event_type": string,
      # "event_id": number,
      # "country": string,
      # "short_desc": string,
      # "long_desc": string
      # "response": string
    # }[]
# }
GET {{base}}/events/incidents
Authorization: {{auth0token}}

### Requests
# Response.data:
  # {
#     incident_id: number
#     acknowledged_by: string
#     closed_by: string
#     priority: number
#     updated_by: string
#     triggering_event: number
#     last_modified: string
#     start_date: number
#     end_date: number
#     notes: string
#     work_order_id: number
# }
GET {{base}}/events/incidents/:id
Authorization: {{auth0token}}

### Events
# QueryString:
#   page: number DEFAULT = 1
#   perPage: number DEFAULT = 10
#   sortBy: keyof Response.data
#   direction: 'asc' | 'desc'
# Response.data:
  # {
    # events: {
    #     event_id: number
    #     event_date: string
    #     priority: number
    #     event_key: string
    #     request: { request_id: string, notes: string, serial_numbers: string[] }
    #     status: string
    #     long_desc: string
    #     event_type: string
    #     incident_count: any
    #     incidents: {
    #         start_date: string
    #         incident_id: number
    #         last_modified: string
    #         response: string
    #     }[]
    # }[]
# }
GET {{base}}/events
Authorization: {{auth0token}}

### Events
# Response.data:{
#   events: {
#         event_id: number
#         event_date: number
#         priority: number
#         event_key: string
#         status: string
#         long_desc: string
#         event_type: string
#         incident_count: any
#         incidents: {
#             start_date: string
#             incident_id: number
#             last_modified: string
#             response: string
#         }[]
#     }[]
# }
GET {{base}}/events/associated/:event_id
Authorization: {{auth0token}}

### Events
# Response.data:
  # {
    # event_id: number,
    # event_date: number,
    # event_type:string,
    # work_order_id: number,
    # short_desc: string
    # long_desc: string
#   }
GET {{base}}/events/:id
Authorization: {{auth0token}}

### Events
# QueryString:
#   filterType: "country" | "type"
# Response.data:
  # {
    # "type": string,
    # "long_desc": string
  # }[] | 
  # { 
    # "country_name": string
    # "country_code": string
  # }[]
GET {{base}}/events/fitler
Authorization: {{auth0token}}

### Events
# Response.data:
  # {
    # "events": number,
    # "incidents": number
  # }
GET {{base}}/events/statistic
Authorization: {{auth0token}}

### Changelog
# QueryString:
#   page: number DEFAULT = 1
#   perPage: number DEFAULT = 10
# Response.data: 
#   changeLogs: 
#   {
#     change_log_id: unknown
#     log_detail: string
#     last_modified: string
#   }[]
GET {{base}}/change-logs
Authorization: {{auth0token}}

### Changelog
# Response.data:     
#   reactions: 
#   {
#     amount: number
#     emoji_code: string
#     pushed: boolean
#   }[]
GET {{base}}/change-logs/:logId/:peopleId
Authorization: {{auth0token}}

### Items
# Response.data: {
#     peripherals: {
#         type: string
#         model: string
#         deployed: number
#         in_stock: number
#     }[]
#     total: number
# }
GET {{base}}/items/peripherals
Authorization: {{auth0token}}

### Items
# Response.data: {
    # total: number
    # recieved_by_atnt: number
    # in_transit: number
    # not_shipped_by_employee: number
# }
GET {{base}}/items/returns
Authorization: {{auth0token}}

### Items
# QueryString: 
#   page: number DEFAULT = 1
#   perPage: number DEFAULT = 10
#   sortBy: keyof Response.data.assets[0] DEFAULT = 'item_detail_id'
#   direction: 'asc' | 'desc' DEFAULT = 'asc'
# Response.data: {
#     assets: {
#         asset_tag: string
#         asset_type: string
#         model: string
#         status: string
#         warranty_date: string
#         requests: {reuqest_id: string}[]
#     }[]
# }
GET {{base}}/items/assets
Authorization: {{auth0token}}

### Items
# Response.data: { total: number }
GET {{base}}/items/assets/total
Authorization: {{auth0token}}

### Items
# Response.data: {
#     total: number
#     deployed: number
#     in_stock: number
#     returned: number
#     quarantined: number
# }
GET {{base}}/items/assets/by-type
Authorization: {{auth0token}}

### Items
# Response.data: {
#     total: number
#     topAssets: { manufacturer: string; model: string; total: number }[],
#     other: number
# }
GET {{base}}/items/assets/make
Authorization: {{auth0token}}

### Support
# QueryString: 
#   status: "active" | "inactive" DEFAULT = "active"
# 
# Response.data: {
#     subject: string
#     desc: string
#     status: 'inactive'
#     date: string
#     type: "issue" | "request" | "feedback"
# }[]
GET {{base}}/support
Authorization: {{auth0token}}

### Me
# Response.data:
  # {
    # "user": {
        # "user_id": number,
        # "first_name": string,
        # "last_name": string,
        # "phone_number_mobile": string,
        # "phone_number_home": string,
        # "status": string,
        # "business_unit": string,
        # "position_title": string,
        # "email": string,
        # "country_name": string,
        # "roles": string[],
        # "picture": string
#   }
# }
GET {{base}}/me
Authorization: {{auth0token}}

### Me
# Body: - all values are optional
#   "first_name": string,             *** If you change one of names, you should put in request body the second
#   "last_name": string,              *** If you change one of names, you should put in request body the second
#   "email": string,                  *** You can't update email and password at the same time
#   "phone_number_mobile": string,
#   "country": string,
#   "status": string,
#   "business_unit": string,
#   "password": string                *** You can't update email and password at the same time
PUT {{base}}/me/update
Authorization: {{auth0token}}
Content-Type: application/json
    {
      "first_name": "Gregory",
      "last_name": "House",
    }

### Me ToS
POST {{base}}/me/tos-sign
Authorization: {{auth0token}}

### Activity Log
# Response.data: {
    # id: string
    # user_first_name: string
    # user_last_name: string
    # user_email: string
    # activity: string
    # date: string
# }
GET {{base}}/activities
Authorization: {{auth0token}}

### Get locations
# Response.data: {
# locations: {
#         country_name: string
#         country_code: string
#     }[]
# }
GET {{base}}/locations
Authorization: {{auth0token}}

### Items modal
# Response.data: {
# {
#     device_make: string
#     device_model: string
#     device_status: string
#     device_serial_number: string
# }
GET {{base}}/items/{serial_number}
Authorization: {{auth0token}}

### Requests data graphs
# Response.data: {
#   total: number
#   categories: {
#     name: string
#     total: number
#   }
# }
GET {{base}}/requests/by-category
Authorization: {{auth0token}}

### Requests data graphs
# Response.data: {
    # total: number
    # other: number
    # top_statuses: {
    #     name: string
    #     total: number
    # }[]
# }
GET {{base}}/requests/by-status
Authorization: {{auth0token}}

### Requests data graphs
# Response.data: {
    # total: number
    # other: number
    # top_services: {
    #     name: string
    #     total: number
    # }[]
# }
GET {{base}}/requests/by-service
Authorization: {{auth0token}}

### Requests data graphs
# Response.data {
    # total: number
    # other: number
    # top_item_types: {
        # name: string
        # total: number
    # }[]
# }
GET {{base}}/requests/advanced-replacements/by-item-type
Authorization: {{auth0token}}