@base=https://fcwsywnkp0.execute-api.us-east-1.amazonaws.com/test
@auth0token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIiwiaXNzIjoiaHR0cHM6Ly9kZXYtaDZwYWttZ2UudXMuYXV0aDAuY29tLyJ9.._T6BBpjOfTAhXJIg.F1fv5oKWV6hlGgqVNoofcvWcK0La987mnyjRClGvd8qQvYVMoBzF9VFWciiCil9GwYOPs-cW4HP8ijw-L4uD177bzdOoYyC7sMVI_OZpWP__YofOUg1lLowHfguOsv0gNNTY30B9QQldooCTGA2pVme9eBv21krH5Eekmt610HbAqklok9hqQEgmBnPkU7LzXleLdcGlOaBaPOTe-DEYX2FYTxyVIT3cx230Q8dHef7UbbgzlpUQkzzagpc4Po9ymGboxgC_Z8qfppBr1Qoju3f_8Os8RmPyeibYYj2LwjpEhtZnBBuFzHSLuYuhjIFEuXLaCSuMuw.QiUxTmcfvMfbQxZSfN7lfg
### User Admin
# QueryString:
#   page: number DEFAULT = 1
#   perPage: number DEFAULT = 10
# Response.data:
  # {
    # "users": {
        # "people_id": number,
        # "first_name": string,
        # "last_name": string,
        # "phone_number_mobile": string,
        # "phone_number_home": string,
        # "status": string,
        # "business_unit": string,
        # "position_title": string,
        # "email_address_home": string,
        # "email_address_work": string,
        # "country_name": string
#   }[]
# }
GET {{base}}/users
Authorization: {{auth0token}}

### User Admin
# Response.data:
  # {
    # "statistic": {
      # "total": number,
      # "active": number
    # }
# }
GET {{base}}/users/statistic
Authorization: {{auth0token}}

### User Admin
# Body: - all values are optional
#   "first_name": string,
#   "last_name": string,
#   "phone_number_mobile": string,
#   "country_code": string,
#   "status": string,
#   "sms_allowed": number,
#   "business_unit": string,
#   "position_title": string
POST {{base}}/users
Authorization: {{auth0token}}
Content-Type: application/json
{
  "first_name": "Lisa",
  "last_name": "Cuddy",
  "phone_number_mobile": "+38 (000) 000-0000",
  "country_code": "UK",
  "status": "Active",
  "sms_allowed": 1,
  "business_unit": "Seed BK-UK",
  "position_title": "Admin"
}

### User Admin
# Path Parameters:
#   id: number - id of user that should be updated
# Body: - all values are optional
#   "first_name": string,
#   "last_name": string,
#   "phone_number_mobile": string,
#   "country_code": string,
#   "status": string,
#   "sms_allowed": number,
#   "business_unit": string,
#   "position_title": string
PUT {{base}}/users/:id
Authorization: {{auth0token}}
Content-Type: application/json
    {
      "first_name": "Gregory",
      "last_name": "House",
      "position_title": "Admin"
    }

### Requests
# QueryString:
#   last: number - the number of days for which the data is received
#   page: number DEFAULT = 1
#   perPage: number DEFAULT = 10
#   sortBy: keyof Response.data.requests DEFAULT = 'event_date'
#   direction: 'asc' | 'desc' DEFAULT = 'desc'
# Response.data: 
# {
  #     requests: {
  #     work_order_id: number
  #     peripheral_description: string
  #     request_type: string
  #     runbook: string
  #     location: string
  #     event_date: string
  #     action: string
  # }[] 
# }
GET {{base}}/requests
Authorization: {{auth0token}}

### Control Center
# QueryString:
#   last: number - the number of days for which the data is received
GET {{base}}/requests/statistic?last
Authorization: {{auth0token}}

### Control Center / Incidents
# QueryString:
#   page: number DEFAULT = 1
#   perPage: number DEFAULT = 10
#   countryCode: string
#   type: string
# Response.data:
  # {
    # incidents: {
      # "incident_id": number,
      # "action": string
      # "latitude": number
      # "longitude": number,
      # "event_type": string,
      # "event_id": number,
      # "country": string,
      # "short_desc": string,
      # "long_desc": string
    # }[]
# }
GET {{base}}/events/incidents
Authorization: {{auth0token}}

### Events
# QueryString:
#   page: number DEFAULT = 1
#   perPage: number DEFAULT = 10
#   countryCode: string
#   type: string
# Response.data:
  # {
    # events: {
      # "event_id": number,
      # "event_type": string,
      # "action": string
      # "country": string,
      # "latitude": number
      # "longitude": number,
      # "short_desc": string,
      # "long_desc": string
    # }[]
# }
GET {{base}}/events
Authorization: {{auth0token}}

### Events
# QueryString:
#   filterType: "country" | "type"
# Response.data:
  # {
    # "type": string,
    # "long_desc": string
  # }[] | 
  # { 
    # "country_name": string
    # "country_code": string
  # }[]
GET {{base}}/events/fitler
Authorization: {{auth0token}}

### Events
# Response.data:
  # {
    # "events": number,
    # "incidents": number
  # }
GET {{base}}/events/statistic
Authorization: {{auth0token}}

### Changelog
# QueryString:
#   page: number DEFAULT = 1
#   perPage: number DEFAULT = 10
# Response.data: 
#   changeLogs: 
#   {
#     change_log_id: unknown
#     log_detail: string
#     last_modified: string
#   }[]
GET {{base}}/change-logs
Authorization: {{auth0token}}

### Changelog
# Response.data:     
#   reactions: 
#   {
#     amount: number
#     emoji_code: string
#     pushed: boolean
#   }[]
GET {{base}}/change-logs/:logId/:peopleId
Authorization: {{auth0token}}

### Items
# Response.data: {
#     peripherals: {
#         type: string
#         model: string
#         deployed: number
#         in_stock: number
#     }[]
#     total: number
# }
GET {{base}}/items/peripherals
Authorization: {{auth0token}}

### Items
# Response.data: {
    # total: number
    # recieved_by_atnt: number
    # in_transit: number
    # not_shipped_by_employee: number
# }
GET {{base}}/items/returns
Authorization: {{auth0token}}

### Items
# Response.data: {
#     assets: {
#         asset_tag: string
#         asset_type: string
#         model: string
#         status: string
#         warranty_date: string
#         requests: string[]
#     }[]
#     total: number
# }
GET {{base}}/items/assets
Authorization: {{auth0token}}

### Items
# Response.data: {
#     total: number
#     deployed: number
#     in_stock: number
#     returned: number
#     quarantined: number
# }
GET {{base}}/items/assets/by-type
Authorization: {{auth0token}}

### Support
# QueryString: 
#   status: "active" | "inactive" DEFAULT = "active"
# 
# Response.data: {
#     subject: string
#     desc: string
#     status: 'inactive'
#     date: string
#     type: "issue" | "request" | "feedback"
# }[]
GET {{base}}/support
Authorization: {{auth0token}}

###
# Response.data: {
#     sub: string
#     given_name: string
#     family_name: string
#     nickname: string
#     name: string
#     picture: string
#     locale: string
#     updated_at: string
#     email: string
#     email_verified: boolean
#     [key: `${string}/roles`]: string[]     *** Should be enabled by Rules in auth0
# }
GET {{base}}/me
Authorization: {{auth0token}}